### ISSUE TITLE
Homepage - Gallery section: There's a white line visible on the bottom portion of the video thumbnail in Firefox and IE browsers.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Adrenalin-Factory#69]
![image](https://cloud.githubusercontent.com/assets/11186304/7178799/260467e4-e464-11e4-9fea-2b98f398e128.png)

**Comment by maluzynel** [comment]
Not yet fixed in IE 8-11

**Comment by ramoncebudigital** [comment]
IE screenshots
![ie8](https://cloud.githubusercontent.com/assets/11186436/7222761/66d20322-e747-11e4-9c32-c08203b083ca.png)
![ie9](https://cloud.githubusercontent.com/assets/11186436/7222762/66d5cbd8-e747-11e4-8418-02c47c80bf70.png)
![ie10](https://cloud.githubusercontent.com/assets/11186436/7222763/66dd6e74-e747-11e4-85bd-71f18ba8fa9d.png)
![ie11](https://cloud.githubusercontent.com/assets/11186436/7222764/677fc7aa-e747-11e4-93cc-2ba9790bac66.png)

**Comment by maluzynel** [comment]
Unable to reproduce issue anymore. this is fixed.
