### ISSUE TITLE
Footer section: Distorted footer section in IE 7 browser.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Adrenalin-Factory#74]
IE 7

![image](https://cloud.githubusercontent.com/assets/11186304/7195693/859d6f74-e4f6-11e4-9eb5-f15f16626282.png)

**Comment by ramoncebudigital** [comment]
working on my end. 
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/7197943/c5b79152-e519-11e4-8aaf-7660f9ca2247.png)
