### ISSUE TITLE
Pages: Got an error when switching the IE browser version mode to IE 8. Unable to test IE 8 version.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Adrenalin-Factory#77]
![image](https://cloud.githubusercontent.com/assets/11186304/7195812/c039501a-e4f8-11e4-90ee-d598538dc09a.png)

**Comment by ramoncebudigital** [comment]
working on my end.

**Comment by maluzynel** [comment]
I'm still able to replicate the issue.

**Comment by ramoncebudigital** [comment]
it's working on our side, tried using other computers
